### ISSUE TITLE
Add support for Intelbras/Tuya devices

### ISSUE THREAD

**Issue by dsants00** [0x5e/homebridge-tuya-platform#217] opened 2023-01-22 14:37 UTC
Hi,

I have added these devices using overriding device config.

**Door/Window sensor**
"category": "mcs",
 "model": "ISA 1001",
 "name": "ISA 1001",
      "status": [
        {
          "code": "doorcontact_state",
          "value": false
        },
        {
          "code": "battery_percentage",
          "value": 95
        },
        {
          "code": "temper_alarm",
          "value": true
        }
      ],

**Siren**
      "category": "sgbj",
      "model": "ISI 1001",
      "name": "ISI 1001",

      "status": [
        {
          "code": "alarm_volume",
          "value": "middle"
        },
        {
          "code": "alarm_switch",
          "value": false
        },
        {
          "code": "battery_percentage",
          "value": 100
        }
      ],

**Motion Sensor**
      "category": "pir",
      "model": "ISM 1001",
      "name": "ISM 1001",
      "status": [
        {
          "code": "pir",
          "value": "none"
        },
        {
          "code": "battery_percentage",
          "value": 100
        }
      ], 

Everything is working fine for the **Door/Window sensor** and **Motion Sensor**, but I'm facing trouble with the **Siren**. And, I'd like to ask for help here.

I see my Siren in my Home app as "Not Supported".

Things I tried:
- Set to Standard Device and DP instruction (Iot Platform).
![image](https://user-images.githubusercontent.com/123310572/213921414-2ea8bee5-6b2c-4e58-be83-7876e65111af.png)

- Cleaned device cached

- restarted child bridge and readded to Home app

- restarted homebridge and readded to Home app

Any suggestions?

**Comment by 0x5e** [comment] 2023-01-22 14:59
`sgbj` is not supported yet, I will add this when I'm free.

**Comment by 0x5e** [comment] 2023-01-22 15:20
Duplicate of #193

**Closed by 0x5e** 2023-01-22 15:20 UTC
Labels: enhancement, help wanted
