### ISSUE TITLE
Tuya Smart lock is showing as not supported device. 

### ISSUE THREAD

**Issue by pratikparmar24292** [0x5e/homebridge-tuya-platform#316] opened 2023-05-27 06:35 UTC
### Prerequisite

- [X] Yes, I've read the readme completely.

### Cache

- [X] Yes, I've cleaned accessory cache and the issue still exists.

### Version

1.7.0-beta.45

### Device Control Mode

Standard Instruction

### Other Infomations

I have added tuya smart lock. its category is "ms". but still shows as not supported in homekit.

**Comment by 0x5e** [comment] 2023-06-01 06:23
duplicate of #315

**Closed by 0x5e** 2023-06-01 06:23 UTC
Labels: bug
